version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=fluffy_bear
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    volumes:
      - /data/mysql
  fluffy-bear-backend:
    image: fluffy-bear-backend-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080                           # host:container
    volumes:
      - /data/spring-boot-app