version: "3"

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=fluffy_bear
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    ports:
      - 3306:3306
  fluffy-bear-backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker-container:3306/fluffy_bear?serverTimezone=UTC
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080 # host:container
    volumes:
      - /data/spring-boot-app #TODO: mapping für Development
  fluffy-bear-frontend:
    image: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend #nicht für Produktion

