version: "3"

services:
   mysql-docker-container:
    image: mysql:5.7.27
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=fluffy_bear
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    ports:
      - 3306:3306